# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- main

pool:
  vmImage: ubuntu-latest
strategy:
  matrix:
    Python27:
      python.version: '2.7'
    Python35:
      python.version: '3.5'
    Python36:
      python.version: '3.6'
    Python37:
      python.version: '3.7'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip  setuptools wheel
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    python -m pip install -U pip
    pip install poetry
    pip install twine
    poetry install
  displayName: Install software

- script: |
    poetry run python -m unittest discover tests/ -v
  displayName: Test software

- script: |
    poetry build
  displayName: Build package
- task: TwineAuthenticate@1
  displayName: Twine Authenticate 
  inputs:
    artifactFeed: 'OneIdentity'
    pythonUploadServiceConnection: pypiTestTania
- script: |
      twine upload -r repo-name --config-file $(PYPIRC_PATH) dist/*.whl
  displayName: 'Upload package to Azure Artifact'
