# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: UsePythonVersion@0
  inputs:
     versionSpec: 3.7
  displayName: 'Use Python 3.7'

- script: |
    python -m pip install --upgrade pip wheel
    pip install poetry
    poetry install
  displayName: 'Install software'

- script: echo current version is $(GitVersion.MajorMinorPatch)
- script: |
    poetry build
  displayName: Build package
  
- task: CopyFiles@2
  displayName: 'Copy files to artifact staging directory'
  inputs:
    SourceFolder: '$(build.sourcesdirectory)'
    Contents: |
      dist/*
    TargetFolder: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()

- task: PublishPipelineArtifact@0
  displayName: 'Publish pipeline artifact'
  inputs:
    artifactName: 'drop'
    targetPath: '$(Build.ArtifactStagingDirectory)'
  condition: succeededOrFailed()

