# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: UsePythonVersion@0
  inputs:
     versionSpec: 3.7
  displayName: 'Use Python 3.7'

- script: |
    python -m pip install --upgrade pip wheel
    pip install twine
    pip install poetry
    poetry install
  displayName: 'Install software'

- script: |
    poetry build
  displayName: Build package

- task: TwineAuthenticate@1
  displayName: Twine Authenticate to testpypi using Service Connection and username __token__
  inputs:
    pythonUploadServiceConnection: testPypiTania
    
- task: CmdLine@2
  inputs:
    script: 'cat $(PYPIRC_PATH)'
  displayName: Print contents of generated .pypirc 

- script: |
      twine upload -r testpypi --verbose --config-file $(PYPIRC_PATH) dist/*
  displayName: Upload package to testpypi